default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV.fetch("POSTGRES_HOST") { "db" } %>
  port: <%= ENV.fetch("POSTGRES_PORT") { 5432 } %>
  database: <%= ENV.fetch("POSTGRES_DB_NAME") { "games_brasil_development" } %>
  username: <%= ENV.fetch("POSTGRES_USER") { "postgres" } %>
  password: <%= ENV.fetch("POSTGRES_PASSWORD") { "postgres" } %>

development:
  <<: *default
  database: games_brasil_development

test:
  <<: *default
  database: games_brasil_test

production:
  primary: &primary_production
    <<: *default
    database: games_brasil_production
    username: games_brasil
    password: <%= ENV["GAMES_BRASIL_DATABASE_PASSWORD"] %>

