default: &default
  adapter: postgresql
  encoding: unicode  
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV.fetch("POSTGRES_HOST") %>
  port: <%= ENV.fetch("POSTGRES_PORT") %>
  database: <%= ENV.fetch("POSTGRES_DB_NAME") %>
  username: <%= ENV.fetch("POSTGRES_USER") %>
  password: <%= ENV.fetch("POSTGRES_PASSWORD") %>

development:
  <<: *default
  database: games_brasil_development

test:
  <<: *default
  database: games_brasil_test

production:
  primary: &primary_production
    <<: *default
    database: games_brasil_production
    username: games_brasil
    password: <%= ENV["GAMES_BRASIL_DATABASE_PASSWORD"] %>

